name: PR Checks

on:
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
      - name: Install dependencies
        run: uv sync --dev
      - name: Run pre-commit
        run: uv run pre-commit run --all-files
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
      - name: Install dependencies
        run: uv sync --dev
      - name: Run pyright
        run: uv run pyright
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
      - name: Install dependencies
        run: uv sync --dev
      - name: Run tests
        run: uv run pytest
